### ISSUE TITLE
Get connection close code

### ISSUE THREAD

**Issue by aurieh** [tonyg/racket-rfc6455#8]
Is it possible to get close code of a connection. I know `ws-conn-closed?` exists, but it only provides a boolean.

**Comment by tonyg** [comment]
It should be possible to get close code and the optional text for rfc6455 connections; hybi00 connections don't have associated close information. What should the API be? Generic API for all connection types, returning e.g. `#f` if no such information is available; or, rfc6455-specific API requiring a special import of the rfc6455 support? Probably the former, I think...?

**Comment by tonyg** [comment]
I've added `ws-conn-close-status` and `ws-conn-close-reason`. Do let me know if they work for you.
